version: '3.8'

services:
  gutosystem:
    image: node:20-alpine
    container_name: gutosystem_front
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://gutosystem.eadescola.online
      - HOST_URL=https://gutosystem.eadescola.online
      - TZ=America/Sao_Paulo
    volumes:
      - /app/frontend-gutosystem-test/gutosystem-front:/app  # Agora aponta para a pasta correta
    command: sh -c "npm install && npm run build && npm start"
    networks:
      - gutosystem_front_net

networks:
  gutosystem_front_net:
    external: true
