version: '3.8'

services:
  gutosystem:
    image: node:20-alpine
    container_name: gutosystem_front
    working_dir: /app
    ports:
      - "3009:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://gutosystem.eadescola.online
      - HOST_URL=https://gutosystem.eadescola.online
      - TZ=America/Sao_Paulo
    volumes:
      - /app/frontend-gutosystem-test/gutosystem-front:/app  # Agora aponta para a pasta correta
    command: sh -c "npm install && npm run build && npm start"
    networks:
      - gutosystem_front_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
      - "traefik.http.routers.frontend-http.rule=Host(`gutosystem.eadescola.online`)"
      - "traefik.http.routers.gutosystem_frontend.entrypoints=websecure"
      - "traefik.http.routers.gutosystem_frontend.rule=Host(`gutosystem.eadescola.online`)"
      - "traefik.http.routers.gutosystem_frontend.tls=true"
      - "traefik.http.routers.gutosystem_frontend.tls.certresolver=leresolver"
      - "traefik.http.services.gutosystem_frontend.loadbalancer.server.port=3000"
networks:
  gutosystem_front_net:
    external: true
