import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";

// Estilos globais e fontes
import 'bulma/css/bulma.css';
import '../components/common/loader/loader.css';
import "@fortawesome/fontawesome-free/css/all.min.css";
import 'primereact/resources/primereact.min.css';
import 'primereact/resources/themes/md-light-indigo/theme.css';
import "primeflex/primeflex.css";
import "../components/layout/menu/Menu.module.css";
import "../app/globals.css";
import "../components/layout/Layout.module.css"; 
import { OrcamentoProvider } from '../contexts/OrcamentoContext';
import "primeicons/primeicons.css";
import { Providers } from "./providers";
import { ManutencaoProvider } from "../contexts/ManutencaoContext";

// Definição das fontes
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata do site
export const metadata: Metadata = {
  title: "Sistema Guto Decorações",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        {/* Configuração segura da Content Security Policy (CSP) */}
        <meta
  httpEquiv="Content-Security-Policy"
  content="default-src 'self'; 
           script-src 'self' 'unsafe-inline' 'unsafe-eval'; 
           connect-src 'self' http://localhost:3000 http://localhost:8080 https://backendgutosystem.eadescola.online https://viacep.com.br https://gutosystem.eadescola.online; 
           style-src 'self' 'unsafe-inline'; 
           img-src 'self' blob: data:; 
           media-src 'self' blob:; 
           object-src 'self' data:;"
/>


      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <OrcamentoProvider>
            <ManutencaoProvider>
              {children}
            </ManutencaoProvider>
          </OrcamentoProvider>
        </Providers>
      </body>
    </html>
  );
}
