export { useCategoriaService } from './categoria.service';
export { useTerceiroService } from './terceiro.service';
export { useProdutoService } from './produto.service';
export { useTipoCaracteristicaService } from './tipoCaracteristica.service';
export { useTerceiroCaracteristicaService} from './terceiroCaracteristica.service';
export { useTerceiroEnderecoService } from './terceiroEndereco.service';
export { useFichaOrcamentoService } from './fichaOrcamento.service';
export { usePedidoOrcamentoService } from './pedidoOrcamento.service';
export { useOrdemServicoManutencaoService } from './ordemServicoManutencao.service';
export { useDashboardService } from './dashboard.service';
export { useMediaService } from './media.service';
export { useFuncoesService } from './funcoes.service';
export { useUsuarioService } from './usuarios.service';
export { useUnidadeMedidaService } from './unidadeMedida.service';